### ISSUE TITLE
Tokenization/merging

### ISSUE THREAD

**Issue by BramVanroy** [wietsedv/xpos#1]
Hi there

Skimmed through the paper and the demo and absolutely love it. Great work! I was playing with the demo, and I came across a small but important bug. To be honest, I do not think this is on the part of your code-base but simply a quirk in the Hugging Face tokenizers. If it is on their part, I'll escalate to their repo.

When I run the following the sentence through the demo, I find that the "retokenization"/merging has an error in it.

> Soms wil ik naar de vogeltjes kijken , maar wil jij dat wel ?

The output is as below, where "jij dat" is merged into "jijdat". This is quite undesirable of course.

![output](https://user-images.githubusercontent.com/2779410/155686431-86c56a7a-21a7-4821-b392-538a460be023.png)

Looking at app.py, it seems that you get the output back from the pipeline - but I just want to check whether you changed anything particular about the XLM-R tokenizer? Otherwise, I assume it's `tokenizer.decode()` that is messing things up, particularly its `clean_up_tokenization_spaces` parameter (untested, might be wrong).

**Comment by wietsedv** [comment]
Thanks Bram! I actually noticed the same yesterday, but I have not looked into the issue yet. I have not changed anything in the tokenizer, so it's probably a general decoder issue. I'll look into it later today and I'll let you know if I find a satisfying solution.

**Comment by BramVanroy** [comment]
Seems an issue with the aggregation strategy in the pipeline. It automatically tries to figure out what the "words" are and then assigns scores based on the subword tokens (average, first token, etc.). But this "detokenization" is different from a tokenizer's `decode()` - which leads to some quirks like this. I'll make a linked topic on the HF issue tracker!

EDIT: well, it makes sense though, since this is a sentencepiece tokenizer. So it doesn't really know what word boundaries are. But I am wondering whether we can't just at least assume that spaces are word boundaries.

PS the "Space" link on [this page](https://huggingface.co/wietsedv/xlm-roberta-base-ft-udpos28-nl) seems broken.

**Comment by wietsedv** [comment]
I fixed the problem in de Space. The XLM-RoBERTa tokenizer does not honer whitespace as forced token seperators. And I used the builtin "first" aggregation strategy of the pipeline so subtokens are merged.

My solution is to aggregate manually based on how XLM-RoBERTa encodes whitespace. My current strategy is to merge subtokens (keep first subtoken tag), but split on whitespace or PUNCT-tagged tokens. Could you let me know if this seems like a good solution to you?

https://huggingface.co/spaces/wietsedv/xpos/commit/0d557da7ce8dc8454c91ac266ca92b21309f95fb

And I'll fix the links!

**Comment by BramVanroy** [comment]
Yeah, that seems sensible indeed. I think such an option is desirable for many other people. Perhaps it could be a different built-in strategy to just use white-spaces? If I find some time, I'll suggest it over at HF. Or you can do a PR yourself if you want of course!

PS: I am not sure whether this scales to other languages though, especially those of other scripts (e.g. Chinese).

Thanks for the quick fix in any case!!

**Comment by KoichiYasuoka** [comment]
Thank you @BramVanroy and @wietsedv for the issue about the tokenization. In Japanese the tokenizer of XML-RoBERTa seems worse:

```
>>> from transformers import AutoTokenizer,AutoModelForTokenClassification,TokenClassificationPipeline
>>> tokenizer=AutoTokenizer.from_pretrained("wietsedv/xlm-roberta-base-ft-udpos28-ja")
>>> model=AutoModelForTokenClassification.from_pretrained("wietsedv/xlm-roberta-base-ft-udpos28-ja")
>>> pipeline=TokenClassificationPipeline(tokenizer=tokenizer,model=model)
>>> print([(t["word"],t["entity"]) for t in pipeline("心がないんだ。")])
[('▁', 'NOUN'), ('心', 'ADJ'), ('がない', 'ADJ'), ('んだ', 'PART'), ('。', 'PUNCT')]
```

As described in `test-s13` of [ja_gsd-ud-test.conllu](https://github.com/UniversalDependencies/UD_Japanese-GSD/blob/master/ja_gsd-ud-test.conllu) the result should be `[('心','NOUN'),('が','ADP'),('ない','ADJ'),('ん','SCONJ'),('だ','AUX'),('。','PUNCT')]`. Umm...

**Comment by wietsedv** [comment]
For the demo, I use an assumption that works well for alphabetic writing systems. A slightly more complex, but I think slightly more robust, workaround might be to check unicode code points of the input text. Then I'll only apply the fix if the majority of characters are latin/cyrillic/etc. In any case, this only applies to the demo. For training and evaluation, the (pre-)tokenization of the training/evaluation data was used.

EDIT: When using the model via code, you should apply your own solution or search for XLM-RoBERTa in general. Without any modifications, tokenization of my models is identical to generic XLM-RobERTa.

**Comment by KoichiYasuoka** [comment]
Thank you @wietsedv for the information about the (pre-)tokenization. I've just tried to tokenize the Japanese sentence by hand:

```py
>>> import torch
>>> from transformers import AutoTokenizer,AutoModelForTokenClassification
>>> tokenizer=AutoTokenizer.from_pretrained("wietsedv/xlm-roberta-base-ft-udpos28-ja")
>>> model=AutoModelForTokenClassification.from_pretrained("wietsedv/xlm-roberta-base-ft-udpos28-ja")
>>> t=["心","が","ない","ん","だ","。"]
>>> v=torch.argmax(model(torch.tensor([tokenizer.convert_tokens_to_ids(t)]))["logits"],dim=2)
>>> print([(x,model.config.id2label[y]) for x,y in zip(t,v[0].tolist())])
[('心', 'NUM'), ('が', 'ADJ'), ('ない', 'ADJ'), ('ん', 'AUX'), ('だ', 'PUNCT'), ('。', 'PUNCT')]
```

Umm... it's better than original XLM-RoBERTa tokenizer but unsatisfied...

**Comment by wietsedv** [comment]
That's unfortunate. But the fine-tuned models and the choice for XLM-RoBERTa are made for cross-lingual evaluation. If you want to have good monolingual Japanese performance, I would rather look at monolingual Japanese models instead of XLM-RoBERTa. Moreover, in a monolingual (non-cross-lingual) setting, large pre-trained models are likely overpowered for POS tagging. Similar performance could likely be gained with simpler (less expensive) models in monolingual settings with sufficient data.
